export const categoryList = [
	{
		id: 1,
		name: 'Lacteos',
	},
	{
		id: 2,
		name: 'Bebidas',
	},
];

export const providersList = [
	{
		id: 1,
		name: 'Parmalat',
	},
	{
		id: 2,
		name: 'Lacteos Los Andes',
	},
];

export const brandList = [
	{
		id: 1,
		name: 'Parmalat',
	},
	{
		id: 2,
		name: 'Frica',
	},
	{
		id: 3,
		name: 'Canaca',
	},
	{
		id: 4,
		name: 'Los Andes',
	},
];

export const productList = [
	{
		id: 1,
		name: 'Leche Completa 1L',
		price: 12.99,
		code: '123',
		category: categoryList[0].name,
		business: 'Distramar',
		isOnPromotion: false,
		isFeature: false,
		stock: 10,
		brand: brandList[0].name,
		provider: providersList[0].name,
		promotionPrice: null,
		image: 'assets/images/LECHE-PARMALAT-800-X-800.jpg',
	},
	{
		id: 2,
		name: 'Jugo de Naranja 2L',
		price: 9.99,
		code: '321',
		category: categoryList[1].name,
		business: 'Distramar',
		isOnPromotion: false,
		isFeature: true,
		stock: 4,
		brand: brandList[1].name,
		provider: providersList[1].name,
		promotionPrice: null,
		image: 'assets/images/JUGO-FRIKA-800-X-800.jpg',
	},
	{
		id: 3,
		name: 'Yogurt Migurt',
		price: 3.99,
		code: '465',
		category: categoryList[1].name,
		business: 'Distramar',
		isOnPromotion: true,
		isFeature: true,
		stock: 9,
		brand: brandList[0].name,
		provider: providersList[0].name,
		promotionPrice: 3.49,
		image: 'assets/images/MIGURT-800-X-800.jpg',
	},
	{
		id: 4,
		name: 'Te de Limón 1.5L',
		price: 7.99,
		code: '823',
		category: categoryList[1].name,
		business: 'Distramar',
		isOnPromotion: false,
		isFeature: false,
		stock: 9,
		brand: brandList[0].name,
		provider: providersList[1].name,
		promotionPrice: null,
		image: 'assets/images/TE-PARMALAT-800-X-800.jpg',
	},
	{
		id: 5,
		name: 'Queso Canaca',
		price: 24.99,
		code: '902',
		category: categoryList[0].name,
		business: 'Distramar',
		isOnPromotion: true,
		isFeature: false,
		stock: 9,
		brand: brandList[2].name,
		provider: providersList[1].name,
		promotionPrice: 20.99,
		image: 'assets/images/QUESO-CANACA-800X800.jpg',
	},
	{
		id: 6,
		name: 'Queso Crema Gaby',
		price: 4.99,
		code: '164',
		category: categoryList[0].name,
		business: 'Distramar',
		isOnPromotion: true,
		isFeature: false,
		stock: 9,
		brand: brandList[3].name,
		provider: providersList[1].name,
		promotionPrice: 3.99,
		image: 'assets/images/QUESO-CREMA800-X-800.jpg',
	},
	{
		id: 7,
		name: 'Leche Completa 1L',
		price: 12.99,
		code: '123',
		category: categoryList[0].name,
		business: 'Distramar',
		isOnPromotion: false,
		isFeature: false,
		stock: 10,
		brand: brandList[0].name,
		provider: providersList[0].name,
		promotionPrice: null,
		image: 'assets/images/LECHE-PARMALAT-800-X-800.jpg',
	},
	{
		id: 8,
		name: 'Leche Completa 1L',
		price: 12.99,
		code: '123',
		category: categoryList[0].name,
		business: 'Distramar',
		isOnPromotion: false,
		isFeature: false,
		stock: 10,
		brand: brandList[0].name,
		provider: providersList[0].name,
		promotionPrice: null,
		image: 'assets/images/LECHE-PARMALAT-800-X-800.jpg',
	},
];

export const clientList = [
	{
		id: 1,
		rut: 'Hermanos Perez CA',
	},
	{
		id: 2,
		rut: 'M&M Licores',
	},
	{
		id: 3,
		rut: 'Mundo pan',
	},
];
